version: "3.9"

services:
  api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/jobtracker
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  worker:
    build: .
    depends_on:
      - redis
      - db
    command: celery -A app.worker worker --loglevel=info
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/jobtracker
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: jobtracker
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    restart: always
  mongo:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"

volumes:
  pgdata:
